import aiBloomStudio from '../assets/images/ai-bloom-studio.mp4';
import aiBonittaBrandingHub from '../assets/images/ai-bonitta-branding-hub.mp4';
import aiEtsyVideoFeed from '../assets/images/ai-etsy-video-feed.mp4';
import aiNodeRecord from '../assets/images/ai-node-record.mp4';
import aiNoorish from '../assets/images/ai-noorish.mp4';
import type { AiCase } from './types';

export const aiCasesEn: AiCase[] = [
  {
    number: '01',
    title: 'Made at Etsy: Video Feed',
    dateLine: '6 hours • 2026 • Figma Make',
    description:
      'A mobile, personalized short-form video feed — letting users see the real people behind each handcrafted item. Designed in Figma and published live with Figma Make.',
    url: 'https://etsy-made-design-concept.figma.site/',
    image: aiEtsyVideoFeed,
  },
  {
    number: '02',
    title: 'Bloom Studio',
    dateLine: '3 days • 2026 • Claude Code',
    description:
      'A responsive virtual flower atelier to create bouquets and share them with friends for special occasions. Built entirely with Claude Code — no pre-design, full prompting, hand-made assets — and deployed straight to GitHub Pages from Claude Code.',
    url: 'https://lucilamtz90.github.io/bloom-studio/',
    image: aiBloomStudio,
  },
  {
    number: '03',
    title: 'Studio Branding Hub',
    dateLine: '5 hours • 2026 • Claude Code',
    description:
      "A responsive B2B platform to centralize branding progress and deliverables for clients, with built-in feedback collection and per-client personalization. Built entirely by prompting — a stylesheet generated by Figma's AI agents was handed to Claude Code, which built it and deployed it straight to GitHub Pages.",
    url: 'https://lucilamtz90.github.io/today-coffee/demo/',
    image: aiBonittaBrandingHub,
  },
  {
    number: '04',
    title: 'Noorish',
    dateLine: '~2 weeks • 2026 • Claude Code',
    description:
      'A personalized 14-day nutrition protocol app — mobile-first, with tailored meal plans, streak badges, and a smart shopping list. This demo runs on static, offline data (no live AI calls), packaged and deployed to GitHub Pages from Claude Code.',
    url: 'https://lucilamtz90.github.io/noorish/',
    image: aiNoorish,
  },
  {
    number: '05',
    title: 'Node Record',
    dateLine: '3 hours • 2026 • Figma, Claude Code',
    description:
      'A web tool that finds musical similarities between a song and other artists, visualized as an interactive node graph. Built in collaboration with Christian, a software developer who implemented the logic — I led the UI design, motion, and UX.',
    creditName: 'Christian',
    creditUrl: 'https://www.linkedin.com/in/cconsuelo/',
    url: 'https://node-record.netlify.app/',
    image: aiNodeRecord,
  },
];
